### ISSUE TITLE
TRY THIS 4.6.

### ISSUE THREAD

**Issue by Tinapolis** [0p3r4t4/PPPUCPP2nd#1]
The solution contains code which is not yet learned up to this point in the book (we dont know yet about bool, true/false)

**Comment by 0p3r4t4** [comment]
Hi. On PPPUCPP 2nd Edition I see that bool variables and literals are present on '3.2 Variables' and '4.3.2 Operators'. I had considered it enough to use it on 4.6.4. But you're free to solve it on a way a bool varable it's not needed.
